version: '3.8'
services:
  api-mock:
    image: danielgtaylor/apisprout
    ports:
      - 8010:8000
    volumes:
      - ./dest/merged.yaml:/merged.yaml
    entrypoint: /usr/local/bin/apisprout /merged.yaml --watch
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8011:8080
    volumes:
      - ./dest/merged.yaml:/usr/share/nginx/html/merged.yaml
    environment:
      API_URL: merged.yaml
  redoc:
    image: redocly/redoc
    ports:
      - 9011:80
    volumes:
      - ./dest/merged.yaml:/usr/share/nginx/html/merged.yaml
    environment:
      SPEC_URL: merged.yaml
  redoc-cli:
    build: ./docker/redoc-cli
    volumes:
      - ./src:/src
      - ./dest:/dest
  swagger-merger:
    build: ./docker/swagger-merger
    command: >
      watch 'swagger-merger -i /src/index.yaml -o /dest/merged.yaml' /src/
    volumes:
      - ./src:/src
      - ./dest:/dest
    environment:
      NODE_PATH: /usr/local/lib/node_modules
    # entrypoint: node ../watch
